# Generated by Django 6.0.3 on 2026-06-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_products_price_products_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='post',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
