# Generated by Django 6.0.5 on 2026-05-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regform',
            name='rep_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regform',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
