# Generated by Django 6.0.3 on 2026-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yamaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('top_speed', models.CharField(max_length=100)),
                ('engine_capacity', models.CharField(max_length=100)),
                ('production_years', models.CharField(max_length=100)),
                ('Transmission', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
    ]
