# Generated by Django 6.1 on 2026-09-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
