# Generated by Django 6.0.5 on 2026-05-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='regModel',
        ),
    ]
