# Generated by Django 6.0.3 on 2026-06-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_users_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='block',
            field=models.BooleanField(default=0),
        ),
    ]
