# Generated by Django 6.0.3 on 2026-06-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='post',
        ),
    ]
