# Generated by Django 6.0.3 on 2026-03-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='highest_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
