# Generated by Django 6.0.5 on 2026-05-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_regform_rep_password_alter_regform_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regform',
            name='rep_password',
        ),
    ]
