# Generated by Django 6.0.3 on 2026-06-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_regform_rep_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regForm',
            new_name='Users',
        ),
    ]
