# Generated by Django 6.0.3 on 2026-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_regform_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
