# Generated by Django 6.0.3 on 2026-06-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='post',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
