# Generated by Django 6.0.3 on 2026-06-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_products_user_id_products_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
    ]
