# Generated by Django 6.0.3 on 2026-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_products_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='post',
            field=models.ImageField(default=1, upload_to='posts'),
            preserve_default=False,
        ),
    ]
