# Generated by Django 6.0.3 on 2026-06-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_products_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.ImageField(default=1, upload_to='Profiles'),
            preserve_default=False,
        ),
    ]
