#  1) დააყენეთ incredible in you face და შექმენით 20 ერორი 

print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")
print("hello) 
car("BMW")