# Generated by Django 6.0.3 on 2026-06-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_users_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(default='https://i.pinimg.com/736x/27/5f/99/275f99923b080b18e7b474ed6155a17f.jpg', upload_to='Profiles'),
        ),
    ]
